#!/bin/sh -e 1

INSTALL_LOCATION="$HOME/bin"
INSTALL_DIRNAME="dotfiles"

path="$INSTALL_LOCATION/$INSTALL_DIRNAME"

mkdir -p $INSTALL_LOCATION
if [ ! -d $path ]; then
  git clone git@github.com:wuputah/dotfiles.git $path
else
  cd $path
  git fetch origin && git rebase origin/master
fi

# fetch janus
if [ ! -d $path/vim ]; then
  git clone git@github.com:wuputah/janus.git $path/vim
else
  cd $path/vim
  git fetch origin && git rebase origin/master
fi

ln -nfs $path/zshrc $HOME/.zshrc
ln -nfs $path/bashrc $HOME/.bashrc
ln -nfs $path/irbrc $HOME/.irbrc
ln -nfs $path/riplrc $HOME/.riplrc
ln -nfs $path/rdebugrc $HOME/.rdebugrc
ln -nfs $path/vimrc $HOME/.vimrc.local
ln -nfs $path/gvimrc $HOME/.gvimrc.local
ln -nfs $path/gemrc $HOME/.gemrc
ln -nfs $path/screenrc $HOME/.screenrc
ln -nfs $path/vim $HOME/.vim
ln -nfs $path/gitignore $HOME/.gitignore.global

[ ! -d $HOME/.ssh ] && mkdir $HOME/.ssh
ln -nfs $path/ssh/config $HOME/.ssh/config

ln -nfs $HOME/.bashrc $HOME/.bash_profile

# build janus
cd $HOME/.vim && rake

if [ ! -f $HOME/.gitconfig ]; then
  cp $path/gitconfig $HOME/.gitconfig
  # probably a better way to obfuscate this... but this should do
  git config --global user.e$(echo ma)il $(echo CDAwuEutaB | tr EABDC p@hdj).c$(echo om)
  # really no way to do this safely
  echo "$HOME/.gitconfig written. You still need to set your github token manually\!"
fi

