#!/bin/sh

set -e

INSTALL_LOCATION="$HOME/code"
INSTALL_DIRNAME="dotfiles"

path="$INSTALL_LOCATION/$INSTALL_DIRNAME"

mkdir -p $INSTALL_LOCATION
if [ ! -d $path ]; then
  git clone git@github.com:wuputah/dotfiles.git $path
fi

# fetch janus
if [ ! -d $path/vim ]; then
  git clone git@github.com:wuputah/janus.git $path/vim
fi

ln -nfs $path/zshrc $HOME/.zshrc
ln -nfs $path/bashrc $HOME/.bashrc
ln -nfs $path/screenrc $HOME/.screenrc
ln -nfs $path/gitignore $HOME/.gitignore.global
ln -nfs $path/irbrc $HOME/.irbrc
ln -nfs $path/riplrc $HOME/.riplrc
ln -nfs $path/rdebugrc $HOME/.rdebugrc
ln -nfs $path/gemrc $HOME/.gemrc
ln -nfs $path/lightningrc $HOME/.lightningrc
ln -nfs $path/janus.rake $HOME/.janus.rake

ln -nfs $path/vimrc $HOME/.vimrc.local
ln -nfs $path/gvimrc $HOME/.gvimrc.local
ln -nfs $path/vim $HOME/.vim

[ ! -d $HOME/.ssh ] && mkdir $HOME/.ssh
ln -nfs $path/ssh/config $HOME/.ssh/config

ln -nfs $HOME/.bashrc $HOME/.bash_profile

if [ ! -f $HOME/.gitconfig ]; then
  cp $path/gitconfig $HOME/.gitconfig
  git config --global user.$(echo ECDAB | tr ABCDE ilmae) $(echo CDAwuEutaBZORG | tr EABDCGROZ p@hdjmoc.)
fi

# build janus
cd $HOME/.vim && rake
